import Head from 'next/head'
import { useRouter } from 'next/router';
import Hero from '../components/Hero'
import Movies from '../components/Movies'
import SignIn from '../components/SignIn';
import { useAuthContext } from '../context/AuthContext'

export default function Home() {
  const { user } = useAuthContext();
  const router = useRouter();

  return (
    <div>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {user ? (
        <>
          <Hero />

          <Movies />
        </>
      ) : (
        <SignIn />
      )}
    </div>
  )
}
