import Head from 'next/head'
import Hero from '../components/Hero'
import Movies from '../components/Movies'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />

      <Movies />
    </div>
  )
}
